### ISSUE TITLE
The style doesn't play well with the Nova light theme

### ISSUE THREAD

**Issue by bernig** [dniccum/nova-documentation#30]
![Capture d’écran du 2023-02-25 21-26-07](https://user-images.githubusercontent.com/10162125/221373563-974d9d71-0ea9-40bd-9011-42f02803358d.png)

A solution would be to allow us to override the CSS through `artisan vendor:publish`?

**Comment by dm-pf** [comment]
@dniccum this is still broken even after your PR #32 because [you're setting darkMode:media](https://github.com/dniccum/nova-documentation/commit/df1c35b5c0ddaf34550448d22db559af9b77ffdf#diff-ddc1067f080930bc48865f4660316a14b21bbc9f9ba85975ce8479342b983d2eR14).

Using darkMode:media in tailwind will ignore the theme already preselected in Nova so you end up with:

- Nova using light theme & nova-documentation displaying text as if dark theme was applied (because OS set to dark mode). This is what happens in the screenshot provided above by @bernig 
- Nova using dark theme & nova-documentation displaying text as if light theme was applied (because OS set to light mode)

We should instead rely on [manually triggered dark mode in tailwind](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) by simply setting darkMode:class.

Nova already sets 'dark' class in the body so everything nova-documentation related should work by default.

Because you're using a tailwind prefix, darkMode:class will not work by default. A hackish workaround that we found works for us, and does not require extra js, is: `darkMode: ['class', 'html[class~=\'dark\']'],`
